# Generated by Django 3.0.3 on 2020-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
