# Generated by Django 3.0.3 on 2020-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0002_batches_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
